DROP DATABASE IF EXISTS leftoverWizard_db;
CREATE DATABASE leftoverWizard_db;

-- user information to store
-- email
-- password
-- ^ Believed to be handled automatically through the config.json and the pasport node module

-- recipe table to store
-- recipe (unknown how many columns or if just 1)
-- recipe link (generated by spoonacular apicall "get recipe information")
-- userID that saved it

-- CREATE TABLE recipes(
--     id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(255),
--     link VARCHAR(255),
--     recipe JSON
--     owner_id INT,
--     FOREING KEY (owner_id) REFERENCES Users(id)
-- );